! generated by gemini - this looks wrong, realy wrong. I will create my own version of it. It's temporary.
PROGRAM decimal_para_binario
  IMPLICIT NONE
  INTEGER :: decimal, resto, i, tamanho
  LOGICAL :: binario(32)  ! Assumindo números de 32 bits

  WRITE(*,*) 'Digite um número decimal:'
  READ(*,*) decimal

  tamanho = 0
  DO WHILE (decimal > 0)
    resto = MOD(decimal, 2)
    binario(tamanho) = resto
    decimal = decimal / 2
    tamanho = tamanho + 1
  END DO

  WRITE(*,*) 'A representação binária é:'
  DO i = tamanho - 1, 0, -1
    WRITE(*,*) binario(i)
  END DO
END PROGRAM decimal_para_binario